---
title: "ENV 797 - Time Series Analysis for Energy and Environment Applications | Spring 2025"
subtitle: "Assignment 1 - Due date 01/16/25"
author: "Rosie Wu"
output: pdf_document
geometry: margin=2.54cm
---

## Directions

Before making any edits to this file, please rename it such that it includes your first and last name (e.g., "LuanaLima_TSA_A01_Sp25.Rmd")

Once you have this renamed file open in RStudio, the first thing you will do is replace "author:" on line 3 with your name. 
Then you will start working through the assignment by  **creating code and output** that answer each question. Be sure to use this assignment document. Your report should contain the answer to each question and any plots/tables you obtained (when applicable).

When you have completed the assignment, **Knit** the text and code into a single PDF file.  Submit this pdf using Sakai. 

## Questions

Q1. What are your previous experiences with time series analysis, R, and Git? 

> Answer: I had some non-systematic experience in R during Undergraduate studies for my Stats course, but that course was focusing on the stats itself, so I didn't gain much understanding in R during that class. Yet, I was able to gain some more systematic and fundamental knowledge in R and Git in the 872 Data Exploration class.

Q2. (Only if you choose to use git) Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file as instructed on the recorded video "Getting started with Git and Github". 

> Answer: https://github.com/ENV797/TSA_Sp25 
I still ran into issue pulling updates from upstream. In my Terminal, my Origin is this link, but my Upstream seems to be https://github.com/TSA, which is a 404 Not Found link when opened in browser. Im also unable to change the Upstream link anymore, as it keeps giving me the "Error, remote upstream already exists." So I'm currently manually uploading files to my local repository through R.

Q3. For this part we just want to see the path to your R project. No need to do anything. The output will be automatically generated once you knit you file. 

> Answer: This is my working directory:

```{r}
getwd()
```

Q4. Copy and paste the link to your forked repository on Github. It should looks like this: "https://github.com/lmmlima/TSA_Sp25"

> Answer: This is my working directory: https://github.com/RuoxiWuRosie/TSA_Sp25 
